blueprint:
  name: IKEA E1743 Handler
  description: Run actions on the press or hold of the on/off buttons on the TRÅDFRI wireless on/off switch.
  domain: automation
  input:
    switch:
      name: Switch
      selector:
        device:
          integration: zha
          manufacturer: IKEA of Sweden
          model: TRADFRI on/off switch
    action_on:
      name: Action For 'On' Button Press
      default:
      selector:
        action:
    action_off:
      name: Action For 'Off' Button Press
      default:
      selector:
        action:
    action_on_hold:
      name: Action For 'On' Button Hold
      default:
      selector:
        action:
    bool_on_hold_repeat:
      name: Repeat 'On' Button Hold Action
      default: false
      selector:
        boolean:
    action_off_hold:
      name: Action For 'Off' Button Hold
      default:
      selector:
        action:
    bool_off_hold_repeat:
      name: Repeat 'Off' Button Hold Action
      default: false
      selector:
        boolean:
mode: queued
trigger:
- platform: event
  event_type: zha_event
  event_data:
    device_id: !input switch
action:
- variables:
    command: "{{ trigger.event.data.command }}"
    cluster_id: "{{ trigger.event.data.cluster_id }}"
    endpoint_id: "{{ trigger.event.data.endpoint_id }}"
    args: "{{ trigger.event.data.args }}"
    repeat_action_on: !input bool_on_hold_repeat
    repeat_action_off: !input bool_off_hold_repeat
- choose:
  - conditions:
      - "{{ command == 'on' }}"
      - "{{ cluster_id == 6 }}"
      - "{{ endpoint_id == 1 }}"
    sequence: !input action_on
  - conditions:
      - "{{ command == 'off' }}"
      - "{{ cluster_id == 6 }}"
      - "{{ endpoint_id == 1 }}"
    sequence: !input action_off
  - conditions:
      - "{{ command == 'move_with_on_off' }}"
      - "{{ cluster_id == 8 }}"
      - "{{ endpoint_id == 1 }}"
      - "{{ args == [0, 83] }}"
      - "{{ repeat_action_on }}"
    sequence:
      - repeat:
          while: "{{ repeat.index < 500 }}"
          sequence: !input action_on_hold
  - conditions:
      - "{{ command == 'move_with_on_off' }}"
      - "{{ cluster_id == 8 }}"
      - "{{ endpoint_id == 1 }}"
      - "{{ args == [0, 83] }}"
    sequence: !input action_on_hold
  - conditions:
      - "{{ command == 'move' }}"
      - "{{ cluster_id == 8 }}"
      - "{{ endpoint_id == 1 }}"
      - "{{ args == [1, 83] }}"
      - "{{ repeat_action_off }}"
    sequence:
      - repeat:
          while: "{{ repeat.index < 500 }}"
          sequence: !input action_off_hold
  - conditions:
      - "{{ command == 'move' }}"
      - "{{ cluster_id == 8 }}"
      - "{{ endpoint_id == 1 }}"
      - "{{ args == [1, 83] }}"
    sequence: !input action_off_hold