blueprint:
  name: IKEA E1743 Handler
  description: Run actions on the press or hold of the on/off buttons on the TRÅDFRI wireless on/off switch.
  domain: automation
  input:
    switch:
      name: Switch
      selector:
        device:
          integration: zha
          manufacturer: IKEA of Sweden
          model: TRADFRI on/off switch
    action_on:
      name: Action For 'On' Button Press
      selector:
        action:
    action_off:
      name: Action For 'Off' Button Press
      selector:
        action:
    action_on_hold:
      name: Action For 'On' Button Hold
      selector:
        action:
    action_off_hold:
      name: Action For 'Off' Button Hold
      selector:
        action:
mode: queued
trigger:
- platform: event
  event_type: zha_event
  event_data:
    device_id: !input switch
action:
- variables:
    command: "{{ trigger.event.data.command }}"
    cluster_id: "{{ trigger.event.data.cluster_id }}"
    endpoint_id: "{{ trigger.event.data.endpoint_id }}"
    args: "{{ trigger.event.data.args }}"
- choose:
  - conditions:
      - "{{ command == 'on' }}"
      - "{{ cluster_id == 6 }}"
      - "{{ endpoint_id == 1 }}"
    sequence: !input action_on
  - conditions:
      - "{{ command == 'off' }}"
      - "{{ cluster_id == 6 }}"
      - "{{ endpoint_id == 1 }}"
    sequence: !input action_off
  - conditions:
      - "{{ command == 'move_with_on_off' }}"
      - "{{ cluster_id == 8 }}"
      - "{{ endpoint_id == 1 }}"
      - "{{ args == [0, 83] }}"
    sequence: !input action_on_hold
  - conditions:
      - "{{ command == 'move' }}"
      - "{{ cluster_id == 8 }}"
      - "{{ endpoint_id == 1 }}"
      - "{{ args == [1, 83] }}"
    sequence: !input action_off_hold